# Autogenerated by LiteX / git: 7acb6d46
set -e
yosys -l icebreaker.rpt icebreaker.ys
nextpnr-ice40 --json icebreaker.json --pcf icebreaker.pcf --asc icebreaker.asc  --pre-pack icebreaker_pre_pack.py --up5k --package sg48 --timing-allow-fail --seed 1 
icepack -s icebreaker.asc icebreaker.bin
