# Autogenerated by LiteX / git: 7acb6d46
set -e
yosys -l radiona_ulx3s.rpt radiona_ulx3s.ys
nextpnr-ecp5 --json radiona_ulx3s.json --lpf radiona_ulx3s.lpf --textcfg radiona_ulx3s.config --45k --package CABGA381 --speed 6 --timing-allow-fail --ignore-loops --seed 1 
ecppack radiona_ulx3s.config --svf radiona_ulx3s.svf --bit radiona_ulx3s.bit  --bootaddr 0    
