# Autogenerated by LiteX / git: 7acb6d46
set -e
yosys -l lattice_crosslink_nx_vip.rpt lattice_crosslink_nx_vip.ys
nextpnr-nexus --json lattice_crosslink_nx_vip.json --pdc lattice_crosslink_nx_vip.pdc --fasm lattice_crosslink_nx_vip.fasm  --device LIFCL-40-9BG400C --timing-allow-fail --seed 1 
prjoxide pack lattice_crosslink_nx_vip.fasm lattice_crosslink_nx_vip.bit
