# Autogenerated by LiteX / git: 7acb6d46
set -e
yosys -l lattice_crosslink_nx_evn.rpt lattice_crosslink_nx_evn.ys
nextpnr-nexus --json lattice_crosslink_nx_evn.json --pdc lattice_crosslink_nx_evn.pdc --fasm lattice_crosslink_nx_evn.fasm  --device LIFCL-40-9BG400C --timing-allow-fail --seed 1 
prjoxide pack lattice_crosslink_nx_evn.fasm lattice_crosslink_nx_evn.bit
